export const GET_CITIES_REQUEST = "GET_CITIES_REQUEST";
export const GET_CITIES = "GET_CITIES";
export const GET_CITIES_FAILURE = "GET_CITIES_FAILURE";
export const GET_WEATHER_REQUEST = "GET_WEATHER_REQUEST";
export const GET_WEATHER = "GET_WEATHER";
export const GET_WEATHER_FAILURE = "GET_WEATHER_FAILURE";
export const SET_CITIES = "SET_CITIES";
